spring:
  application:
    name: CountryRegionService

server:
  port: 8480

geo-lite:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:5000, localhost:5001
    ServerListRefreshInterval: 15000