spring:
  application:
    name: spring-cloud-ribbon

server:
  port: 8480

ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9090
    ServerListRefreshInterval: 15000