version: '3'

services:


#  country-region:
#    image: 'country-region:latest'
#    container_name: country-region
#    depends_on:
#      - db
#      - geo-lite
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/country_region
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=43ahegib
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - CR_URL=http://geo-lite:9090/Geo2LiteCountry
#      - GEO.URL=https://download.geonames.org/
#    ports:
#      - 8480:8480





  geo-lite:
    image: 'geo-lite:latest'
#    container_name: geo-lite
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
    depends_on:
      - geo-lite
    ports:
      - "4000:4000"


#  db:
#    image: 'postgres:13.1-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_DB=country_region
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=43ahegib
#    ports:
#      - 5432:5432